apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: python-backend-pipeline
  namespace: ${{ values.component_id }}-dev
  labels:
    backstage.io/kubernetes-id: ${{ values.component_id }}    
spec:
  params:
  - default: quay.io
    name: image-host
    type: string
  - default: your-org
    name: image-organization
    type: string
  - default: python-backend
    name: image-name
    type: string
  - default: "0.1"
    name: image-tag
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: ${{ values.source_repository }}
    - name: revision
      value: ""
    - name: refspec
      value: ""
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "false"
    - name: crtFileName
      value: ca-bundle.crt
    - name: subdirectory
      value: ""
    - name: sparseCheckoutDirectories
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: ""
    - name: httpsProxy
      value: ""
    - name: noProxy
      value: ""
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
    - name: userHome
      value: /home/git
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build-image
    params:
    - name: IMAGE
      value: $(params.image-host)/$(params.image-organization)/$(params.image-name):$(params.image-tag)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:00795fafdab9bbaa22cd29d1faa1a01e604e4884a2c935c1bf8e3d1f0ad1c084
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Containerfile
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: PUSH_EXTRA_ARGS
      value: ""
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace    
  workspaces:
  - name: workspace
